using MonoMod;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public class patch_TIMapRegionTemplate : TIMapRegionTemplate 
{
    public static float GetSeaTravelMultiplier(CoastRegion region1, CoastRegion region2, bool SuezAccess, bool PanamaAccess, bool arcticOpen = false)
    {
        float num = patch_TIMapRegionTemplate._defaultSeaTravelModifiersNEW[region1][region2];
        //if (!SuezAccess && TIMapRegionTemplate.SuezRoute(region1, region2, arcticOpen))
        //{
        //    num *= 1.6f;
        //}
        //if (!PanamaAccess && TIMapRegionTemplate.PanamaRoute(region1, region2, arcticOpen))
        //{
        //    num *= 1.4f;
        //}
        return num;
    }

    static readonly Dictionary<CoastRegion, Dictionary<CoastRegion, float>> _defaultSeaTravelModifiersNEW = new Dictionary<CoastRegion, Dictionary<CoastRegion, float>>
    {
        {
            CoastRegion.Arctic, //Great Ocean North
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1f
                },
                {
                    CoastRegion.BlackMed,
                    1.25f
                },
                {
                    CoastRegion.PacificCarib,
                    1.25f
                },
                {
                    CoastRegion.Caribbean,
                    1.1f
                },
                {
                    CoastRegion.Indian,
                    3.5f
                },
                {
                    CoastRegion.Mediterranean,
                    3f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    1.1f
                },
                {
                    CoastRegion.NortheastPacific,
                    2.8f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    1.1f
                },
                {
                    CoastRegion.NorthwestPacific,
                    3.2f
                },
                {
                    CoastRegion.SouthAtlantic,
                    1.1f
                },
                {
                    CoastRegion.IndianMed,
                    1.45f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.1f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                    1.25f
                },
                {
                    CoastRegion.SouthwestPacific,
                    2.1f
                }
            }
        },
        {
            CoastRegion.NortheastAtlantic, //Great Ocean East
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.1f
                },
                {
                    CoastRegion.BlackMed,
                    1.20f
                },
                {
                    CoastRegion.PacificCarib,
                    1.25f
                },
                {
                    CoastRegion.Caribbean,
                    1.3f
                },
                {
                    CoastRegion.Indian,
                    1.4f
                },
                {
                    CoastRegion.IndianMed,
                    1.4f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    1f
                },
                {
                    CoastRegion.NortheastPacific,
                   3.5f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    1.1f
                },
                {
                    CoastRegion.NorthwestPacific,
                    5f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                    1f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.25f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.75f
                }
            }
        },
        {
            CoastRegion.NorthwestAtlantic, //Great Ocean West
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.1f
                },
                {
                    CoastRegion.BlackMed,
                    1.20f
                },
                {
                    CoastRegion.PacificCarib,
                    1.25f
                },
                {
                    CoastRegion.Caribbean,
                    1.3f
                },
                {
                    CoastRegion.Indian,
                    1.4f
                },
                {
                    CoastRegion.IndianMed,
                    1.4f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    1.1f
                },
                {
                    CoastRegion.NortheastPacific,
                    3f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    1f
                },
                {
                    CoastRegion.NorthwestPacific,
                    4.2f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                    1.1f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.25f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.75f
                }
            }
        },
         {
            CoastRegion.MedNorthAtlantic, //Great Ocean South
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.25f
                },
                {
                    CoastRegion.PacificCarib,
                    1.45f
                },
                {
                    CoastRegion.BlackMed,
                    1.15f
                },
                {
                    CoastRegion.Caribbean,
                    1f
                },
                {
                    CoastRegion.Indian,
                    1.25f
                },
                 {
                    CoastRegion.IndianMed,
                    1.35f
                },
                {
                    CoastRegion.Mediterranean,
                    1.4f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    1f
                },
                {
                    CoastRegion.NortheastPacific,
                    1.25f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    2.5f
                },
                {
                    CoastRegion.NorthwestPacific,
                    1.5f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                    1f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.35f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.55f
                }
            }
        },
          {
            CoastRegion.BlackMed, //The Bridge Ocean
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.25f
                },
                {
                    CoastRegion.PacificCarib,
                    1.1f
                },
                {
                    CoastRegion.IndianMed,
                    1.35f
                },
            {
                    CoastRegion.BlackMed,
                    1f
                },
                {
                    CoastRegion.Caribbean,
                    1.15f
                },
                {
                    CoastRegion.Indian,
                    1.25f
                },
                {
                    CoastRegion.Mediterranean,
                    1.15f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    1.75f
                },
                {
                    CoastRegion.NortheastPacific,
                    1.55f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    2.25f
                },
                {
                    CoastRegion.NorthwestPacific,
                    2.35f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                   1.15f
                },
                {
                    CoastRegion.SouthChinaSea,
                    1.75f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.55f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.7f
                }
            }
        },
          {
            CoastRegion.IndianMed, //Zabri-Hyp Coast
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.45f
                },
                {
                    CoastRegion.PacificCarib,
                    1.1f
                },
                {
                    CoastRegion.IndianMed,
                    1f
                },
            {
                    CoastRegion.BlackMed,
                    1.35f
                },
                {
                    CoastRegion.Caribbean,
                    1.1f
                },
                {
                    CoastRegion.Indian,
                    1.1f
                },
                {
                    CoastRegion.Mediterranean,
                    1.15f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    1.65f
                },
                {
                    CoastRegion.NortheastPacific,
                    1.55f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    1.55f
                },
                {
                    CoastRegion.NorthwestPacific,
                   2.25f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                   1.35f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.65f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.25f
                }
            }
        },
           {
            CoastRegion.PacificCarib, //Ocean of the Storm
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.25f
                },
                {
                    CoastRegion.PacificCarib,
                    1f
                },
                {
                    CoastRegion.IndianMed,
                    1.1f
                },
            {
                    CoastRegion.BlackMed,
                    1.1f
                },
                {
                    CoastRegion.Caribbean,
                    1.1f
                },
                {
                    CoastRegion.Indian,
                    1.1f
                },
                {
                    CoastRegion.Mediterranean,
                    1.15f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    1.75f
                },
                {
                    CoastRegion.NortheastPacific,
                    1.35f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    1.25f
                },
                {
                    CoastRegion.NorthwestPacific,
                    1.65f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                   1.45f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.45f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.3f
                }
            }
        },
        {
            CoastRegion.Caribbean, //The Wild Ocean
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.25f
                },
                {
                    CoastRegion.PacificCarib,
                    1.1f
                },
                {
                    CoastRegion.IndianMed,
                    1.2f
                },
            {
                    CoastRegion.BlackMed,
                    1.2f
                },
                {
                    CoastRegion.Caribbean,
                    1f
                },
                {
                    CoastRegion.Indian,
                    1.05f
                },
                {
                    CoastRegion.Mediterranean,
                    1.15f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    2.25f
                },
                {
                    CoastRegion.NortheastPacific,
                    1.35f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    2.25f
                },
                {
                    CoastRegion.NorthwestPacific,
                    1.65f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                   1.55f
                },
                {
                    CoastRegion.SouthChinaSea,
                    1.75f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.15f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.7f
                }
            }
        },
        {
            CoastRegion.Indian, //The Tame Ocean
            new Dictionary<CoastRegion, float>
            {
                        {
                    CoastRegion.Arctic,
                    1.25f
                },
                {
                    CoastRegion.PacificCarib,
                    1.1f
                },
                {
                    CoastRegion.IndianMed,
                    1.2f
                },
            {
                    CoastRegion.BlackMed,
                    1.2f
                },
                {
                    CoastRegion.Caribbean,
                    1.05f
                },
                {
                    CoastRegion.Indian,
                    1f
                },
                {
                    CoastRegion.Mediterranean,
                    1.15f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    2.25f
                },
                {
                    CoastRegion.NortheastPacific,
                    1.35f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    2.25f
                },
                {
                    CoastRegion.NorthwestPacific,
                    1.65f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                   1.55f
                },
                {
                    CoastRegion.SouthChinaSea,
                    1.75f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.15f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.7f
                }
            }
        },
        {
            CoastRegion.NortheastPacific, //East Eetruscan Ocean
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.75f
                },
                {
                    CoastRegion.PacificCarib,
                    1.15f
                },
                {
                    CoastRegion.IndianMed,
                    1.15f
                },
                {
                    CoastRegion.Caribbean,
                    1.3f
                },
                {
                    CoastRegion.Indian,
                    1.35f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                    2.00f
                },
                {
                    CoastRegion.NortheastAtlantic,
                   3.5f
                },
                {
                    CoastRegion.NortheastPacific,
                    1f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    3f
                },
                {
                    CoastRegion.NorthwestPacific,
                    1.15f
                },
                {
                    CoastRegion.BlackMed,
                    1.5f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.85f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1f
                }
            }
        },
        {
            CoastRegion.NorthwestPacific, //West Etruscan Ocean
            new Dictionary<CoastRegion, float>
            {
             {
                    CoastRegion.Arctic,
                    1.95f
                },
                {
                    CoastRegion.PacificCarib,
                    1.35f
                },
                {
                    CoastRegion.IndianMed,
                    1.35f
                },
                {
                    CoastRegion.Caribbean,
                    1.4f
                },
                {
                    CoastRegion.Indian,
                    1.65f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                    2.25f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    5f
                },
                {
                    CoastRegion.NortheastPacific,
                    1.25f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    4.2f
                },
                {
                    CoastRegion.NorthwestPacific,
                    1.0f
                },
                {
                    CoastRegion.BlackMed,
                    1.75f
                },
                {
                    CoastRegion.SoutheastPacific,
                    2.15f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.35f
                }
            }
        },
        {
            CoastRegion.SoutheastPacific, //East Griffionian Ocean
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.1f
                },
                {
                    CoastRegion.IndianMed,
                    1.75f
                },
                {
                    CoastRegion.BlackMed,
                    1.7f
                },
                {
                    CoastRegion.Caribbean,
                    1.3f
                },
                {
                    CoastRegion.Indian,
                    1.15f
                },
                {
                    CoastRegion.PacificCarib,
                    1.35f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    1.15f
                },
                {
                    CoastRegion.NortheastPacific,
                    1.85f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    1.1f
                },
                {
                    CoastRegion.NorthwestPacific,
                    2.15f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                    1.3f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.1f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.45f
                }
            }
        },
        {
            CoastRegion.SouthwestPacific, //West Griffionian Ocean
            new Dictionary<CoastRegion, float>
            {
                {
                    CoastRegion.Arctic,
                    1.1f
                },
                {
                    CoastRegion.IndianMed,
                    1.15f
                },
                {
                    CoastRegion.BlackMed,
                    1.25f
                },
                {
                    CoastRegion.Caribbean,
                    1.1f
                },
                {
                    CoastRegion.Indian,
                    1.35f
                },
                {
                    CoastRegion.PacificCarib,
                    1.15f
                },
                {
                    CoastRegion.NortheastAtlantic,
                    1.95f
                },
                {
                    CoastRegion.NortheastPacific,
                    1.05f
                },
                {
                    CoastRegion.NorthwestAtlantic,
                    1.9f
                },
                {
                    CoastRegion.NorthwestPacific,
                    1.25f
                },
                {
                    CoastRegion.MedNorthAtlantic,
                    1.5f
                },
                {
                    CoastRegion.SoutheastPacific,
                    1.45f
                },
                {
                    CoastRegion.SouthwestPacific,
                    1.0f
                }
            }
        }
    };
}